import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
const here = path.dirname(fileURLToPath(import.meta.url));
const packagesDir = path.resolve(here, '..', '..');
const outFile = path.resolve(here, '..', 'src', 'provider-catalog.generated.ts');
const entries: unknown[] = [];
for (const dir of await fs.readdir(packagesDir, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue;
  try {
    const pkg = JSON.parse(await fs.readFile(path.join(packagesDir, dir.name, 'package.json'), 'utf8')) as { name?: string; moxxy?: { catalog?: Record<string, unknown> } };
    if (!pkg.name || !pkg.moxxy?.catalog) continue;
    entries.push({ id: pkg.name.replace(/^@moxxy\/plugin-/, ''), packageName: pkg.name, installSpec: pkg.name, ...pkg.moxxy.catalog });
  } catch { /* not a package */ }
}
entries.sort((a, b) => String((a as { packageName: string }).packageName).localeCompare(String((b as { packageName: string }).packageName)));
await fs.writeFile(outFile, `// AUTO-GENERATED by scripts/gen-catalog.mts — DO NOT EDIT.\nimport type { PluginCatalogEntry } from './catalog-types.js';\nexport const PROVIDER_PLUGIN_CATALOG = ${JSON.stringify(entries, null, 2)} as const satisfies ReadonlyArray<PluginCatalogEntry>;\n`);
console.log(`gen-catalog: wrote ${entries.length} provider manifest(s)`);
