// AUTO-GENERATED by scripts/gen-catalog.mts — DO NOT EDIT.
import type { PluginCatalogEntry } from './catalog-types.js';
export const PROVIDER_PLUGIN_CATALOG = [
  {
    "id": "provider-anthropic",
    "packageName": "@moxxy/plugin-provider-anthropic",
    "installSpec": "@moxxy/plugin-provider-anthropic",
    "label": "Anthropic (Claude)",
    "description": "Anthropic Claude models. Needs an API key (moxxy init or /vault).",
    "provides": [
      {
        "category": "provider",
        "name": "anthropic"
      }
    ],
    "provider": {
      "auth": "key",
      "defaultModel": "claude-opus-5",
      "recommended": true
    }
  },
  {
    "id": "provider-claude-code",
    "packageName": "@moxxy/plugin-provider-claude-code",
    "installSpec": "@moxxy/plugin-provider-claude-code",
    "label": "Claude (Pro/Max sign-in)",
    "description": "Claude models through an existing Claude Code subscription sign-in.",
    "provides": [
      {
        "category": "provider",
        "name": "claude-code"
      }
    ],
    "provider": {
      "auth": "oauth",
      "defaultModel": "claude-sonnet-4-6"
    }
  },
  {
    "id": "provider-google",
    "packageName": "@moxxy/plugin-provider-google",
    "installSpec": "@moxxy/plugin-provider-google",
    "label": "Google (Gemini)",
    "description": "Google Gemini models. Needs an API key (moxxy init or /vault).",
    "provides": [
      {
        "category": "provider",
        "name": "google"
      }
    ],
    "provider": {
      "auth": "key"
    }
  },
  {
    "id": "provider-local",
    "packageName": "@moxxy/plugin-provider-local",
    "installSpec": "@moxxy/plugin-provider-local",
    "label": "Local (Ollama)",
    "description": "Local models via an Ollama/OpenAI-compatible server. No API key needed.",
    "provides": [
      {
        "category": "provider",
        "name": "local"
      }
    ],
    "provider": {
      "auth": "none"
    }
  },
  {
    "id": "provider-openai",
    "packageName": "@moxxy/plugin-provider-openai",
    "installSpec": "@moxxy/plugin-provider-openai",
    "label": "OpenAI (GPT)",
    "description": "OpenAI GPT models. Needs an API key (moxxy init or /vault).",
    "provides": [
      {
        "category": "provider",
        "name": "openai"
      }
    ],
    "provider": {
      "auth": "key"
    }
  },
  {
    "id": "provider-openai-codex",
    "packageName": "@moxxy/plugin-provider-openai-codex",
    "installSpec": "@moxxy/plugin-provider-openai-codex",
    "label": "OpenAI Codex (ChatGPT sign-in)",
    "description": "Codex models through a ChatGPT subscription sign-in.",
    "provides": [
      {
        "category": "provider",
        "name": "openai-codex"
      }
    ],
    "provider": {
      "auth": "oauth"
    }
  },
  {
    "id": "provider-xai",
    "packageName": "@moxxy/plugin-provider-xai",
    "installSpec": "@moxxy/plugin-provider-xai",
    "label": "xAI (Grok)",
    "description": "xAI Grok models. Needs an API key (moxxy init or /vault).",
    "provides": [
      {
        "category": "provider",
        "name": "xai"
      }
    ],
    "provider": {
      "auth": "key"
    }
  },
  {
    "id": "provider-zai",
    "packageName": "@moxxy/plugin-provider-zai",
    "installSpec": "@moxxy/plugin-provider-zai",
    "label": "z.ai (GLM)",
    "description": "z.ai GLM models (API + GLM Coding Plan). Needs an API key (moxxy init or /vault).",
    "provides": [
      {
        "category": "provider",
        "name": "zai"
      },
      {
        "category": "provider",
        "name": "zai-plan"
      }
    ],
    "provider": {
      "auth": "key"
    }
  }
] as const satisfies ReadonlyArray<PluginCatalogEntry>;
