import { randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { writeFileAtomic } from '@moxxy/sdk/server';

/**
 * Transactional bookkeeping for self-update. Every change to a user-scope
 * artifact (a plugin directory or a skill file) is bracketed by a transaction:
 * the target is snapshotted before edits, a persisted journal tracks state and
 * failed attempts, and a rollback restores the snapshot (or deletes a freshly
 * created artifact). This module is filesystem-only and imports no moxxy core,
 * so it is trivially unit-testable against a temp directory.
 */

export type TargetKind = 'plugin' | 'skill';

export type TxnState = 'open' | 'verified' | 'committed' | 'rolled_back' | 'escalated';

export interface TxnTarget {
  readonly kind: TargetKind;
  readonly name: string;
  /** Absolute path to the artifact (a directory for plugins, a file for skills). */
  readonly path: string;
}

export interface TxnAttempt {
  readonly at: string;
  readonly stage: string;
  readonly ok: boolean;
  readonly message: string;
}

/** Registered contribution names per kind — used to diff what a change added. */
export type RegistrySnapshot = Record<string, ReadonlyArray<string>>;

export interface Journal {
  readonly txnId: string;
  readonly createdAt: string;
  updatedAt: string;
  readonly target: TxnTarget;
  /** Whether the artifact existed before this transaction. false ⇒ rollback deletes it. */
  readonly existedBefore: boolean;
  state: TxnState;
  attempts: TxnAttempt[];
  /** Registry contributions captured at begin time, for an added-since diff. */
  registryBefore?: RegistrySnapshot;
}

/** Names present in `after` but not in `before`, per kind. Empty keys dropped. */
export function diffSnapshot(before: RegistrySnapshot, after: RegistrySnapshot): RegistrySnapshot {
  const out: Record<string, ReadonlyArray<string>> = {};
  for (const key of Object.keys(after)) {
    const had = new Set(before[key] ?? []);
    const added = (after[key] ?? []).filter((n) => !had.has(n));
    if (added.length > 0) out[key] = added;
  }
  return out;
}

/** Max failed verify cycles for one transaction before we force escalation. */
export const MAX_FAILED_ATTEMPTS = 2;

const NAME_SEGMENT_RE = /^[A-Za-z0-9._-]+$/;

/**
 * Paths excluded from a transaction snapshot. `node_modules` is reproducible
 * from package.json (verify re-runs `npm install`), `.git` would balloon the
 * copy, and `dist` is regenerated by the build — copying any of them turns a
 * source snapshot into a multi-hundred-MB recursive copy of the dependency tree
 * on every begin and every restore, which is slow and can exhaust disk.
 */
const SNAPSHOT_EXCLUDE = new Set(['node_modules', '.git', 'dist']);

/**
 * Build an `fs.cp` filter that skips excluded directory basenames so snapshots
 * stay source-only — but never excludes the copy root itself (a plugin could,
 * per NAME_SEGMENT_RE, legitimately be named e.g. `dist`).
 */
function snapshotFilter(root: string): (src: string) => boolean {
  return (src) => src === root || !SNAPSHOT_EXCLUDE.has(path.basename(src));
}

export function selfUpdateRoot(moxxyDir: string): string {
  return path.join(moxxyDir, 'self-update', 'txns');
}

export function txnDir(moxxyDir: string, txnId: string): string {
  return path.join(selfUpdateRoot(moxxyDir), txnId);
}

/**
 * Resolve the on-disk target for a (kind, name). Throws on unsafe names so a
 * model-supplied name can never escape the user artifact directories.
 */
export function resolveTarget(moxxyDir: string, kind: TargetKind, name: string): TxnTarget {
  if (!NAME_SEGMENT_RE.test(name)) {
    throw new Error(
      `invalid ${kind} name "${name}": only letters, digits, dot, dash and underscore are allowed`,
    );
  }
  const p =
    kind === 'plugin'
      ? path.join(moxxyDir, 'plugins', name)
      : path.join(moxxyDir, 'skills', `${name}.md`);
  return { kind, name, path: p };
}

export function newTxnId(now: Date = new Date()): string {
  const stamp = now.toISOString().replace(/[:.]/g, '-');
  // crypto UUID (not Math.random): two begins in the same second must never
  // collide on the txn dir, which beginTransaction's recursive mkdir would
  // silently share — clobbering an existing txn's journal + before snapshot.
  const rand = randomUUID().slice(0, 8);
  return `${stamp}-${rand}`;
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Open a transaction: snapshot the current target (if any) into the txn dir
 * and write the initial journal. Safe to call for a not-yet-existing target.
 */
export async function beginTransaction(opts: {
  readonly moxxyDir: string;
  readonly kind: TargetKind;
  readonly name: string;
  readonly now?: Date;
}): Promise<Journal> {
  const now = opts.now ?? new Date();
  const target = resolveTarget(opts.moxxyDir, opts.kind, opts.name);
  const txnId = newTxnId(now);
  const dir = txnDir(opts.moxxyDir, txnId);
  await fs.mkdir(dir, { recursive: true });

  const existedBefore = await pathExists(target.path);
  if (existedBefore) {
    const before = path.join(dir, 'before');
    await fs.cp(target.path, before, { recursive: true, filter: snapshotFilter(target.path) });
  }

  const journal: Journal = {
    txnId,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    target,
    existedBefore,
    state: 'open',
    attempts: [],
  };
  await writeJournal(opts.moxxyDir, journal);
  return journal;
}

export async function writeJournal(moxxyDir: string, journal: Journal): Promise<void> {
  journal.updatedAt = new Date().toISOString();
  const file = path.join(txnDir(moxxyDir, journal.txnId), 'journal.json');
  await writeFileAtomic(file, JSON.stringify(journal, null, 2) + '\n');
}

export async function readJournal(moxxyDir: string, txnId: string): Promise<Journal> {
  const file = path.join(txnDir(moxxyDir, txnId), 'journal.json');
  const raw = await fs.readFile(file, 'utf8');
  return JSON.parse(raw) as Journal;
}

export async function listTransactions(moxxyDir: string): Promise<ReadonlyArray<Journal>> {
  const root = selfUpdateRoot(moxxyDir);
  let ids: string[];
  try {
    ids = (await fs.readdir(root, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name);
  } catch {
    return [];
  }
  const out: Journal[] = [];
  for (const id of ids) {
    try {
      out.push(await readJournal(moxxyDir, id));
    } catch {
      // ignore half-written / corrupt txn dirs
    }
  }
  return out.sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export function recordAttempt(journal: Journal, attempt: Omit<TxnAttempt, 'at'>): void {
  journal.attempts.push({ at: new Date().toISOString(), ...attempt });
}

export function failedAttemptCount(journal: Journal): number {
  return journal.attempts.filter((a) => !a.ok).length;
}

/**
 * Restore the target to its pre-transaction state: copy the snapshot back, or
 * delete the artifact if it was newly created. Idempotent.
 *
 * The snapshot is source-only (SNAPSHOT_EXCLUDE drops node_modules/.git/dist),
 * so a blanket `rm -rf` of the target before copying would wipe the installed
 * runtime deps — and nothing re-installs them, leaving a plugin that fails to
 * load on the very next deps.reload(). To keep the working `node_modules` (and
 * the other reproducible-but-uncaptured dirs) across a MODIFICATION rollback, we
 * remove only the captured source entries and overlay the snapshot back on top,
 * never touching the excluded dirs. A newly-created target (no snapshot) is still
 * deleted wholesale.
 */
export async function restoreSnapshot(moxxyDir: string, journal: Journal): Promise<void> {
  const { target, existedBefore } = journal;
  if (!existedBefore) {
    await fs.rm(target.path, { recursive: true, force: true });
    return;
  }
  const before = path.join(txnDir(moxxyDir, journal.txnId), 'before');
  // A skill target is a single file, not a directory — replace it outright.
  if (target.kind !== 'plugin') {
    await fs.rm(target.path, { recursive: true, force: true });
    await fs.cp(before, target.path, { recursive: true, filter: snapshotFilter(before) });
    return;
  }
  // Plugin directory: clear only the non-excluded entries (the source the
  // snapshot captured) so the live node_modules/.git/dist survive intact, then
  // copy the source snapshot back over them.
  let entries: string[] = [];
  try {
    entries = (await fs.readdir(target.path, { withFileTypes: true })).map((e) => e.name);
  } catch {
    // Target dir vanished — recreate it from the snapshot below.
  }
  for (const name of entries) {
    if (SNAPSHOT_EXCLUDE.has(name)) continue;
    await fs.rm(path.join(target.path, name), { recursive: true, force: true });
  }
  await fs.mkdir(target.path, { recursive: true });
  await fs.cp(before, target.path, { recursive: true, filter: snapshotFilter(before) });
}

/** Keep the most recent `keep` terminal transactions; delete older ones. */
export async function gcTransactions(moxxyDir: string, keep: number): Promise<void> {
  const all = await listTransactions(moxxyDir);
  const terminal = all.filter(
    (j) => j.state === 'committed' || j.state === 'rolled_back' || j.state === 'escalated',
  );
  for (const j of terminal.slice(keep)) {
    await fs.rm(txnDir(moxxyDir, j.txnId), { recursive: true, force: true });
  }
}
