/**
 * Pure helpers for the moxxy interactive setup. The interactive UX lives in
 * `@moxxy/cli`'s wizard runner; this module only owns rendering the user's
 * selections as a `~/.moxxy/config.yaml` PREVIEW for the review step, so the
 * renderer can be unit-tested without spinning up a terminal. The actual
 * persistence is a comment-preserving doc merge (`applyInitConfig` in
 * `@moxxy/config`) — this preview mirrors the unified `plugins:` tree it writes.
 */

/** How the wizard authenticates a given provider. */
export type ProviderAuthKind = 'apiKey' | 'oauth';

export interface SetupChoice {
  readonly id: string;
  readonly label: string;
  readonly description?: string;
  /** When true, the option is rendered but cannot be selected (with the disabled reason). */
  readonly disabled?: string;
}

export interface SetupSelections {
  readonly providers: ReadonlyArray<string>;
  readonly apiKeys: Record<string, string>;
  readonly primary: string;
  readonly model: string | null;
  readonly mode: string;
  readonly embedder: string;
  /** Optional per-provider auth kind. Missing entries default to `'apiKey'`. */
  readonly authKinds?: Record<string, ProviderAuthKind>;
  /**
   * Opt-in plugin-security selection. Omit to leave the security block
   * out of the generated YAML entirely (= default, off behavior).
   */
  readonly security?: {
    readonly enabled: boolean;
    readonly isolator?: string;
  };
}

/**
 * Quote a YAML scalar only when it would otherwise be misparsed. Wizard
 * selections (provider/model/mode/embedder/isolator ids) come from a known
 * catalog so the common case is a plain bareword (`anthropic`, `default`) that
 * must stay unquoted — the renderer's tests assert that exact shape. But these
 * ids are not guaranteed special-char-free, and this writes a config FILE: an
 * id carrying a YAML indicator (`:`, `#`, leading `-`/`?`/`*`/`&`/`!`/`%`/`@`,
 * a quote, brackets/braces, or whitespace) would silently produce a malformed
 * or mis-parsed `moxxy.config.yaml`. Double-quote and escape those so the
 * output always round-trips. Dep-free on purpose (this module stays runtime
 * dependency-light; the full `yaml` lib is test-only).
 */
export function yamlScalar(value: string): string {
  // Empty string must be quoted (a bare empty value parses as null).
  if (value === '') return '""';
  // Plain-safe: starts with an alnum and contains only the limited set that
  // can never trigger YAML's flow/indicator parsing. Covers every real
  // provider/model/mode id (letters, digits, `-`, `_`, `.`, `/`, `+`).
  if (/^[A-Za-z0-9][A-Za-z0-9._/+-]*$/.test(value)) return value;
  // Otherwise double-quote with the minimal JSON-compatible escaping YAML
  // accepts inside a double-quoted scalar (backslash, quote, control chars).
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

/**
 * Render the wizard's selections as the unified `plugins:` tree that
 * `applyInitConfig` persists to `~/.moxxy/config.yaml`. PREVIEW ONLY — shown in
 * the review step; the real write is a doc merge that also preserves the
 * package ledger + comments. Mirrors the clean-slate schema exactly:
 * `plugins.provider.default` (+ `items.<name>.model`, `fallbacks`),
 * `plugins.mode.default`, `plugins.embedder.default`, and the top-level
 * `security` block. The provider's API key is NOT referenced here — like
 * `moxxy provision`, it lives in the vault under its canonical name and the
 * credential resolver finds it there, so no `${vault:...}` ref is written.
 */
export function renderYaml(sel: SetupSelections): string {
  const fallbacks = sel.providers.filter((p) => p !== sel.primary);
  const lines: string[] = ['# ~/.moxxy/config.yaml — generated by `moxxy init`', ''];
  lines.push('plugins:');
  lines.push('  provider:');
  lines.push(`    default: ${yamlScalar(sel.primary)}`);
  if (sel.model) {
    lines.push('    items:');
    lines.push(`      ${yamlScalar(sel.primary)}:`);
    lines.push(`        model: ${yamlScalar(sel.model)}`);
  }
  if (fallbacks.length > 0) {
    lines.push('    fallbacks:');
    for (const f of fallbacks) lines.push(`      - ${yamlScalar(f)}`);
  }
  lines.push('  mode:');
  lines.push(`    default: ${yamlScalar(sel.mode)}`);
  if (sel.embedder !== 'tfidf') {
    lines.push('  embedder:');
    lines.push(`    default: ${yamlScalar(sel.embedder)}`);
  }
  if (sel.security?.enabled) {
    lines.push('security:');
    lines.push('  enabled: true');
  }
  lines.push('');
  return lines.join('\n');
}
