// AUTO-GENERATED by scripts/gen-requirements.mts — DO NOT EDIT.
// Compiles each bundled package's package.json#moxxy.requirements into the
// binary so requirement gating + toposort survive bundling. Regenerated by
// the cli `build` script; committed so typecheck works standalone.
import type { MoxxyRequirement } from '@moxxy/sdk';

export const BUILTIN_REQUIREMENTS: Readonly<
  Record<string, ReadonlyArray<MoxxyRequirement>>
> = {
  "@moxxy/mode-deep-research": [
    {
      "kind": "plugin",
      "name": "@moxxy/plugin-subagents",
      "state": "registered",
      "hint": "Enable @moxxy/plugin-subagents — deep-research fans out sub-queries via ctx.subagents."
    }
  ],
  "@moxxy/plugin-channel-slack": [
    {
      "kind": "plugin",
      "name": "@moxxy/plugin-vault",
      "hint": "slack resolves the vault from the service registry for its bot token + signing secret + pairing; @moxxy/plugin-vault must load first"
    }
  ],
  "@moxxy/plugin-oauth": [
    {
      "kind": "plugin",
      "name": "@moxxy/plugin-vault",
      "hint": "oauth resolves the vault from the service registry to store tokens; @moxxy/plugin-vault must load first"
    }
  ],
  "@moxxy/plugin-stt-whisper-codex": [
    {
      "kind": "plugin",
      "name": "@moxxy/plugin-provider-openai-codex",
      "state": "registered",
      "hint": "Enable @moxxy/plugin-provider-openai-codex."
    },
    {
      "kind": "plugin",
      "name": "@moxxy/plugin-stt-whisper",
      "state": "registered",
      "hint": "Enable @moxxy/plugin-stt-whisper for shared audio helpers."
    },
    {
      "kind": "plugin",
      "name": "@moxxy/plugin-vault",
      "state": "registered",
      "hint": "whisper-codex resolves the vault from the service registry for the Codex OAuth token; @moxxy/plugin-vault must load first."
    }
  ],
  "@moxxy/plugin-telegram": [
    {
      "kind": "plugin",
      "name": "@moxxy/plugin-vault",
      "hint": "telegram resolves the vault from the service registry for its bot token + pairing; @moxxy/plugin-vault must load first"
    }
  ]
} as const satisfies Readonly<
  Record<string, ReadonlyArray<MoxxyRequirement>>
>;
