// AUTO-GENERATED by scripts/gen-requirements.mts — DO NOT EDIT.
// Compiles each bundled package's package.json#moxxy.requirements into the
// binary so requirement gating + toposort survive bundling. Regenerated by
// the cli `build` script; committed so typecheck works standalone.
import type { MoxxyRequirement } from '@moxxy/sdk';

export const BUILTIN_REQUIREMENTS: Readonly<
  Record<string, ReadonlyArray<MoxxyRequirement>>
> = {} as const satisfies Readonly<
  Record<string, ReadonlyArray<MoxxyRequirement>>
>;
